import type { Metadata } from 'next'
import { Karla } from 'next/font/google'
import './globals.css'

const karla = Karla({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Eslint with Prettier and Tailwind',
  description: 'Generated by Fernando Hiroshi',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" className="bg-gradient !scroll-smooth">
      <body className={karla.className}>{children}</body>
    </html>
  )
}
